apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: rollout-application
  name: transcription-service
  namespace: app
spec:
  selector:
    app: transcription
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 50051
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/instance: rollout-application
  name: ollama
  namespace: app
spec:
  type: LoadBalancer
  selector:
    name: ollama
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
      app.kubernetes.io/instance: rollout-application
  name: api-ss
  namespace: app
spec:
  selector:
    app: api-ss
  ports:
  - name: http
    port: 80
    targetPort: 8900
    protocol: TCP
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: multilang-translation
    app.kubernetes.io/instance: rollout-application
  name: multilang-translation-service
  namespace: app
spec:
  selector:
    app: multilang-translation
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1401
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: srt-translation
    app.kubernetes.io/instance: rollout-application
  name: srt-translation-service
  namespace: app
spec:
  selector:
    app: srt-translation
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1402
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: srt-to-audio
    app.kubernetes.io/instance: rollout-application
  name: srt-to-audio-service
  namespace: app
spec:
  selector:
    app: srt-to-audio
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 1403
  type: LoadBalancer
